{
    'name': 'POS Venezuela Dual Currency + IGTF',
    'summary': 'Referencias USD en POS, conversión Bs/USD e IGTF usando tasa BCV',
    'version': '19.0.1.0.2',
    'category': 'Sales/Point of Sale',
    'author': 'Simon Alberto Rodriguez Pacheco',
    'website': 'https://github.com/simonrodriguezpacheco',
    'license': 'LGPL-3',
    'depends': [
        'point_of_sale',
        'pos_online_payment',
        'bcv_rate_update_venezuela',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/pos_payment_method_views.xml',
        'views/pos_payment_views.xml',
        'views/pos_session_views.xml',
        'views/pos_order_views.xml',
        'views/pos_config_kanban_views.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'pos_venezuela_dual_currency/static/src/app/screens/payment_screen/payment_screen/payment_screen.css',
            'pos_venezuela_dual_currency/static/src/app/shared_state.js',
            'pos_venezuela_dual_currency/static/src/app/models/pos_order.js',
            'pos_venezuela_dual_currency/static/src/app/screens/product_screen/control_buttons/control_buttons.js',
            'pos_venezuela_dual_currency/static/src/app/screens/product_screen/control_buttons/control_buttons.xml',
            'pos_venezuela_dual_currency/static/src/app/screens/product_screen/control_buttons/custom_button/custom_button.js',
            'pos_venezuela_dual_currency/static/src/app/screens/product_screen/control_buttons/custom_button/custom_button.xml',
            'pos_venezuela_dual_currency/static/src/app/screens/product_screen/order_widget/order_widget.js',
            'pos_venezuela_dual_currency/static/src/app/screens/product_screen/order_widget/order_widget.xml',
            'pos_venezuela_dual_currency/static/src/app/screens/payment_screen/payment_screen/payment_screen.js',
            'pos_venezuela_dual_currency/static/src/app/screens/payment_screen/payment_lines/payment_lines.js',
            'pos_venezuela_dual_currency/static/src/app/screens/payment_screen/payment_lines/payment_lines.xml',
            'pos_venezuela_dual_currency/static/src/app/screens/payment_screen/payment_lines/custom_payment_lines/custom_payment_lines.js',
            'pos_venezuela_dual_currency/static/src/app/screens/payment_screen/payment_lines/custom_payment_lines/custom_payment_lines.xml',
            'pos_venezuela_dual_currency/static/src/app/screens/payment_screen/usd_total/usd_total.js',
            'pos_venezuela_dual_currency/static/src/app/screens/payment_screen/usd_total/usd_total.xml',
            'pos_venezuela_dual_currency/static/src/app/screens/ticket_screen/ticket_screen.js',
            'pos_venezuela_dual_currency/static/src/app/screens/ticket_screen/ticket_screen.xml',
        ],
    },
    'application': False,
    'installable': True,
    'auto_install': False,
}
