services:
  db-leads:
    extends:
      file: docker-compose.leads.yml
      service: db-leads
  web-leads:
    extends:
      file: docker-compose.leads.yml
      service: web-leads

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

networks:
  odoo_network_19:
    external: true
